# Generated by Django 6.0.4 on 2026-04-14 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intersection_type', models.CharField(choices=[('cross_intersection', 'Cross Intersection'), ('t_intersection', 'T Intersection'), ('y_intersection', 'Y Intersection'), ('x_intersection', 'X Intersection')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersections', to='smart_traffic_light.admin')),
            ],
            options={
                'db_table': 'intersections',
            },
        ),
        migrations.CreateModel(
            name='Pedestrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north', models.BooleanField(default=False)),
                ('south', models.BooleanField(default=False)),
                ('east', models.BooleanField(default=False)),
                ('west', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedestrian_config', to='smart_traffic_light.intersection')),
            ],
            options={
                'db_table': 'pedestrians',
            },
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_type', models.CharField(choices=[('one_way', 'One Way'), ('two_way', 'Two Way'), ('mixed', 'Mixed')], max_length=20)),
                ('vertical_road_mode', models.CharField(blank=True, choices=[('one_way', 'One Way'), ('two_way', 'Two Way')], max_length=20, null=True)),
                ('horizontal_road_mode', models.CharField(blank=True, choices=[('one_way', 'One Way'), ('two_way', 'Two Way')], max_length=20, null=True)),
                ('vertical_direction', models.CharField(choices=[('north_to_south', 'North to South'), ('south_to_north', 'South to North'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('horizontal_direction', models.CharField(choices=[('east_to_west', 'East to West'), ('west_to_east', 'West to East'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='road_type_config', to='smart_traffic_light.intersection')),
            ],
            options={
                'db_table': 'road_types',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='smart_traffic_light.admin')),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='smart_traffic_light.intersection')),
            ],
            options={
                'db_table': 'system_logs',
            },
        ),
    ]
