# Generated by Django 6.0.4 on 2026-04-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_traffic_light', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='intersection',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='intersection',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
