# Generated by Django 6.0.4 on 2026-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_traffic_light', '0002_remove_systemlog_admin_remove_intersection_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadtype',
            name='horizontal_direction',
            field=models.CharField(blank=True, choices=[('east_to_west', 'East to West'), ('west_to_east', 'West to East'), ('auto', 'Auto')], default='auto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roadtype',
            name='vertical_direction',
            field=models.CharField(blank=True, choices=[('north_to_south', 'North to South'), ('south_to_north', 'South to North'), ('auto', 'Auto')], default='auto', max_length=20, null=True),
        ),
    ]
