# Generated by Django 6.0.4 on 2026-04-21 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_traffic_light', '0003_alter_roadtype_horizontal_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.IntegerField(default=0)),
                ('max_time', models.IntegerField(default=0)),
                ('time_per_vehicle', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller_times', to='smart_traffic_light.intersection')),
            ],
            options={
                'db_table': 'controller_times',
            },
        ),
    ]
