# Generated by Django 6.0.4 on 2026-04-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_traffic_light', '0004_controllertimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerRoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north_roi', models.JSONField(blank=True, null=True)),
                ('south_roi', models.JSONField(blank=True, null=True)),
                ('east_roi', models.JSONField(blank=True, null=True)),
                ('west_roi', models.JSONField(blank=True, null=True)),
                ('north_camera', models.IntegerField(blank=True, null=True)),
                ('south_camera', models.IntegerField(blank=True, null=True)),
                ('east_camera', models.IntegerField(blank=True, null=True)),
                ('west_camera', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller_roi', to='smart_traffic_light.intersection')),
            ],
            options={
                'db_table': 'controller_rois',
            },
        ),
    ]
