# Generated by Django 6.0.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_traffic_light', '0005_controllerroi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllerroi',
            name='east_camera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controllerroi',
            name='north_camera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controllerroi',
            name='south_camera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controllerroi',
            name='west_camera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
